from motor.motor_asyncio import AsyncIOMotorDatabase


async def ensure_indexes(database: AsyncIOMotorDatabase) -> None:
    await database["users"].create_index("email", unique=True)
    await database["auth_sessions"].create_index("refresh_token_hash", unique=True)
    await database["auth_sessions"].create_index("user_id")
    await database["auth_sessions"].create_index("expires_at", expireAfterSeconds=0)
    await database["sites"].create_index([("user_id", 1), ("updated_at", -1)])
    await database["sites"].create_index([("user_id", 1), ("code", 1)], unique=True)
    await database["sites"].create_index("tariff_id")
    await database["projects"].create_index([("user_id", 1), ("updated_at", -1)])
    await database["projects"].create_index("site_id")
    await database["projects"].create_index("bess_catalog_id")
    await database["projects"].create_index("latest_analysis_run_id")
    await database["projects"].create_index("dataset_ids")
    await database["tariffs"].create_index("code", unique=True)
    await database["tariffs"].create_index([("status", 1), ("effective_from", -1)])
    await database["tariffs"].create_index("voltage_level")
    await database["bess_catalog"].create_index("code", unique=True)
    await database["bess_catalog"].create_index([("status", 1), ("version", -1)])
    await database["analysis_runs"].create_index([("user_id", 1), ("created_at", -1)])
    await database["analysis_runs"].create_index([("user_id", 1), ("analysis_type", 1)])
    await database["analysis_runs"].create_index("project_id")
    await database["analysis_runs"].create_index("bess_catalog_id")
    await database["files"].create_index([("user_id", 1), ("updated_at", -1)])
    await database["files"].create_index("project_id")
    await database["files"].create_index("sha256")
    await database["datasets"].create_index([("user_id", 1), ("updated_at", -1)])
    await database["datasets"].create_index("project_id")
    await database["datasets"].create_index("file_id", unique=True)
